/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeedKitsRouteImport } from './routes/seed-kits'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces_.$workspaceId'
import { Route as DevDreamProgressRouteImport } from './routes/_dev.dream-progress'
import { Route as WorkspacesWorkspaceIdWebhooksRouteImport } from './routes/workspaces_.$workspaceId_.webhooks'
import { Route as WorkspacesWorkspaceIdSessionsRouteImport } from './routes/workspaces_.$workspaceId_.sessions'
import { Route as WorkspacesWorkspaceIdQueueRouteImport } from './routes/workspaces_.$workspaceId_.queue'
import { Route as WorkspacesWorkspaceIdPeersRouteImport } from './routes/workspaces_.$workspaceId_.peers'
import { Route as WorkspacesWorkspaceIdDreamsRouteImport } from './routes/workspaces_.$workspaceId_.dreams'
import { Route as WorkspacesWorkspaceIdConclusionsRouteImport } from './routes/workspaces_.$workspaceId_.conclusions'
import { Route as WorkspacesWorkspaceIdSessionsSessionIdRouteImport } from './routes/workspaces_.$workspaceId_.sessions_.$sessionId'
import { Route as WorkspacesWorkspaceIdPeersPeerIdRouteImport } from './routes/workspaces_.$workspaceId_.peers_.$peerId'
import { Route as WorkspacesWorkspaceIdPeersPeerIdPlaygroundRouteImport } from './routes/workspaces_.$workspaceId_.peers_.$peerId_.playground'
import { Route as WorkspacesWorkspaceIdPeersPeerIdChatRouteImport } from './routes/workspaces_.$workspaceId_.peers_.$peerId_.chat'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedKitsRoute = SeedKitsRouteImport.update({
  id: '/seed-kits',
  path: '/seed-kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces_/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDreamProgressRoute = DevDreamProgressRouteImport.update({
  id: '/_dev/dream-progress',
  path: '/dream-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdWebhooksRoute =
  WorkspacesWorkspaceIdWebhooksRouteImport.update({
    id: '/workspaces_/$workspaceId_/webhooks',
    path: '/workspaces/$workspaceId/webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdSessionsRoute =
  WorkspacesWorkspaceIdSessionsRouteImport.update({
    id: '/workspaces_/$workspaceId_/sessions',
    path: '/workspaces/$workspaceId/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdQueueRoute =
  WorkspacesWorkspaceIdQueueRouteImport.update({
    id: '/workspaces_/$workspaceId_/queue',
    path: '/workspaces/$workspaceId/queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdPeersRoute =
  WorkspacesWorkspaceIdPeersRouteImport.update({
    id: '/workspaces_/$workspaceId_/peers',
    path: '/workspaces/$workspaceId/peers',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdDreamsRoute =
  WorkspacesWorkspaceIdDreamsRouteImport.update({
    id: '/workspaces_/$workspaceId_/dreams',
    path: '/workspaces/$workspaceId/dreams',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdConclusionsRoute =
  WorkspacesWorkspaceIdConclusionsRouteImport.update({
    id: '/workspaces_/$workspaceId_/conclusions',
    path: '/workspaces/$workspaceId/conclusions',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdSessionsSessionIdRoute =
  WorkspacesWorkspaceIdSessionsSessionIdRouteImport.update({
    id: '/workspaces_/$workspaceId_/sessions_/$sessionId',
    path: '/workspaces/$workspaceId/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdPeersPeerIdRoute =
  WorkspacesWorkspaceIdPeersPeerIdRouteImport.update({
    id: '/workspaces_/$workspaceId_/peers_/$peerId',
    path: '/workspaces/$workspaceId/peers/$peerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute =
  WorkspacesWorkspaceIdPeersPeerIdPlaygroundRouteImport.update({
    id: '/workspaces_/$workspaceId_/peers_/$peerId_/playground',
    path: '/workspaces/$workspaceId/peers/$peerId/playground',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdPeersPeerIdChatRoute =
  WorkspacesWorkspaceIdPeersPeerIdChatRouteImport.update({
    id: '/workspaces_/$workspaceId_/peers_/$peerId_/chat',
    path: '/workspaces/$workspaceId/peers/$peerId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/explore': typeof ExploreRoute
  '/fleet': typeof FleetRoute
  '/governance': typeof GovernanceRoute
  '/resources': typeof ResourcesRoute
  '/seed-kits': typeof SeedKitsRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/workspaces': typeof WorkspacesRoute
  '/dream-progress': typeof DevDreamProgressRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workspaces/$workspaceId/conclusions': typeof WorkspacesWorkspaceIdConclusionsRoute
  '/workspaces/$workspaceId/dreams': typeof WorkspacesWorkspaceIdDreamsRoute
  '/workspaces/$workspaceId/peers': typeof WorkspacesWorkspaceIdPeersRoute
  '/workspaces/$workspaceId/queue': typeof WorkspacesWorkspaceIdQueueRoute
  '/workspaces/$workspaceId/sessions': typeof WorkspacesWorkspaceIdSessionsRoute
  '/workspaces/$workspaceId/webhooks': typeof WorkspacesWorkspaceIdWebhooksRoute
  '/workspaces/$workspaceId/peers/$peerId': typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces/$workspaceId/peers/$peerId/chat': typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
  '/workspaces/$workspaceId/peers/$peerId/playground': typeof WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/explore': typeof ExploreRoute
  '/fleet': typeof FleetRoute
  '/governance': typeof GovernanceRoute
  '/resources': typeof ResourcesRoute
  '/seed-kits': typeof SeedKitsRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/workspaces': typeof WorkspacesRoute
  '/dream-progress': typeof DevDreamProgressRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workspaces/$workspaceId/conclusions': typeof WorkspacesWorkspaceIdConclusionsRoute
  '/workspaces/$workspaceId/dreams': typeof WorkspacesWorkspaceIdDreamsRoute
  '/workspaces/$workspaceId/peers': typeof WorkspacesWorkspaceIdPeersRoute
  '/workspaces/$workspaceId/queue': typeof WorkspacesWorkspaceIdQueueRoute
  '/workspaces/$workspaceId/sessions': typeof WorkspacesWorkspaceIdSessionsRoute
  '/workspaces/$workspaceId/webhooks': typeof WorkspacesWorkspaceIdWebhooksRoute
  '/workspaces/$workspaceId/peers/$peerId': typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces/$workspaceId/peers/$peerId/chat': typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
  '/workspaces/$workspaceId/peers/$peerId/playground': typeof WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/explore': typeof ExploreRoute
  '/fleet': typeof FleetRoute
  '/governance': typeof GovernanceRoute
  '/resources': typeof ResourcesRoute
  '/seed-kits': typeof SeedKitsRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/workspaces': typeof WorkspacesRoute
  '/_dev/dream-progress': typeof DevDreamProgressRoute
  '/workspaces_/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workspaces_/$workspaceId_/conclusions': typeof WorkspacesWorkspaceIdConclusionsRoute
  '/workspaces_/$workspaceId_/dreams': typeof WorkspacesWorkspaceIdDreamsRoute
  '/workspaces_/$workspaceId_/peers': typeof WorkspacesWorkspaceIdPeersRoute
  '/workspaces_/$workspaceId_/queue': typeof WorkspacesWorkspaceIdQueueRoute
  '/workspaces_/$workspaceId_/sessions': typeof WorkspacesWorkspaceIdSessionsRoute
  '/workspaces_/$workspaceId_/webhooks': typeof WorkspacesWorkspaceIdWebhooksRoute
  '/workspaces_/$workspaceId_/peers_/$peerId': typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  '/workspaces_/$workspaceId_/sessions_/$sessionId': typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces_/$workspaceId_/peers_/$peerId_/chat': typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
  '/workspaces_/$workspaceId_/peers_/$peerId_/playground': typeof WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/explore'
    | '/fleet'
    | '/governance'
    | '/resources'
    | '/seed-kits'
    | '/settings'
    | '/telemetry'
    | '/workspaces'
    | '/dream-progress'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/conclusions'
    | '/workspaces/$workspaceId/dreams'
    | '/workspaces/$workspaceId/peers'
    | '/workspaces/$workspaceId/queue'
    | '/workspaces/$workspaceId/sessions'
    | '/workspaces/$workspaceId/webhooks'
    | '/workspaces/$workspaceId/peers/$peerId'
    | '/workspaces/$workspaceId/sessions/$sessionId'
    | '/workspaces/$workspaceId/peers/$peerId/chat'
    | '/workspaces/$workspaceId/peers/$peerId/playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/explore'
    | '/fleet'
    | '/governance'
    | '/resources'
    | '/seed-kits'
    | '/settings'
    | '/telemetry'
    | '/workspaces'
    | '/dream-progress'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/conclusions'
    | '/workspaces/$workspaceId/dreams'
    | '/workspaces/$workspaceId/peers'
    | '/workspaces/$workspaceId/queue'
    | '/workspaces/$workspaceId/sessions'
    | '/workspaces/$workspaceId/webhooks'
    | '/workspaces/$workspaceId/peers/$peerId'
    | '/workspaces/$workspaceId/sessions/$sessionId'
    | '/workspaces/$workspaceId/peers/$peerId/chat'
    | '/workspaces/$workspaceId/peers/$peerId/playground'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/explore'
    | '/fleet'
    | '/governance'
    | '/resources'
    | '/seed-kits'
    | '/settings'
    | '/telemetry'
    | '/workspaces'
    | '/_dev/dream-progress'
    | '/workspaces_/$workspaceId'
    | '/workspaces_/$workspaceId_/conclusions'
    | '/workspaces_/$workspaceId_/dreams'
    | '/workspaces_/$workspaceId_/peers'
    | '/workspaces_/$workspaceId_/queue'
    | '/workspaces_/$workspaceId_/sessions'
    | '/workspaces_/$workspaceId_/webhooks'
    | '/workspaces_/$workspaceId_/peers_/$peerId'
    | '/workspaces_/$workspaceId_/sessions_/$sessionId'
    | '/workspaces_/$workspaceId_/peers_/$peerId_/chat'
    | '/workspaces_/$workspaceId_/peers_/$peerId_/playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ExploreRoute: typeof ExploreRoute
  FleetRoute: typeof FleetRoute
  GovernanceRoute: typeof GovernanceRoute
  ResourcesRoute: typeof ResourcesRoute
  SeedKitsRoute: typeof SeedKitsRoute
  SettingsRoute: typeof SettingsRoute
  TelemetryRoute: typeof TelemetryRoute
  WorkspacesRoute: typeof WorkspacesRoute
  DevDreamProgressRoute: typeof DevDreamProgressRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  WorkspacesWorkspaceIdConclusionsRoute: typeof WorkspacesWorkspaceIdConclusionsRoute
  WorkspacesWorkspaceIdDreamsRoute: typeof WorkspacesWorkspaceIdDreamsRoute
  WorkspacesWorkspaceIdPeersRoute: typeof WorkspacesWorkspaceIdPeersRoute
  WorkspacesWorkspaceIdQueueRoute: typeof WorkspacesWorkspaceIdQueueRoute
  WorkspacesWorkspaceIdSessionsRoute: typeof WorkspacesWorkspaceIdSessionsRoute
  WorkspacesWorkspaceIdWebhooksRoute: typeof WorkspacesWorkspaceIdWebhooksRoute
  WorkspacesWorkspaceIdPeersPeerIdRoute: typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  WorkspacesWorkspaceIdSessionsSessionIdRoute: typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  WorkspacesWorkspaceIdPeersPeerIdChatRoute: typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
  WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute: typeof WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed-kits': {
      id: '/seed-kits'
      path: '/seed-kits'
      fullPath: '/seed-kits'
      preLoaderRoute: typeof SeedKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId': {
      id: '/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/dream-progress': {
      id: '/_dev/dream-progress'
      path: '/dream-progress'
      fullPath: '/dream-progress'
      preLoaderRoute: typeof DevDreamProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/webhooks': {
      id: '/workspaces_/$workspaceId_/webhooks'
      path: '/workspaces/$workspaceId/webhooks'
      fullPath: '/workspaces/$workspaceId/webhooks'
      preLoaderRoute: typeof WorkspacesWorkspaceIdWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/sessions': {
      id: '/workspaces_/$workspaceId_/sessions'
      path: '/workspaces/$workspaceId/sessions'
      fullPath: '/workspaces/$workspaceId/sessions'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/queue': {
      id: '/workspaces_/$workspaceId_/queue'
      path: '/workspaces/$workspaceId/queue'
      fullPath: '/workspaces/$workspaceId/queue'
      preLoaderRoute: typeof WorkspacesWorkspaceIdQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/peers': {
      id: '/workspaces_/$workspaceId_/peers'
      path: '/workspaces/$workspaceId/peers'
      fullPath: '/workspaces/$workspaceId/peers'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/dreams': {
      id: '/workspaces_/$workspaceId_/dreams'
      path: '/workspaces/$workspaceId/dreams'
      fullPath: '/workspaces/$workspaceId/dreams'
      preLoaderRoute: typeof WorkspacesWorkspaceIdDreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/conclusions': {
      id: '/workspaces_/$workspaceId_/conclusions'
      path: '/workspaces/$workspaceId/conclusions'
      fullPath: '/workspaces/$workspaceId/conclusions'
      preLoaderRoute: typeof WorkspacesWorkspaceIdConclusionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/sessions_/$sessionId': {
      id: '/workspaces_/$workspaceId_/sessions_/$sessionId'
      path: '/workspaces/$workspaceId/sessions/$sessionId'
      fullPath: '/workspaces/$workspaceId/sessions/$sessionId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/peers_/$peerId': {
      id: '/workspaces_/$workspaceId_/peers_/$peerId'
      path: '/workspaces/$workspaceId/peers/$peerId'
      fullPath: '/workspaces/$workspaceId/peers/$peerId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPeersPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/peers_/$peerId_/playground': {
      id: '/workspaces_/$workspaceId_/peers_/$peerId_/playground'
      path: '/workspaces/$workspaceId/peers/$peerId/playground'
      fullPath: '/workspaces/$workspaceId/peers/$peerId/playground'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPeersPeerIdPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/peers_/$peerId_/chat': {
      id: '/workspaces_/$workspaceId_/peers_/$peerId_/chat'
      path: '/workspaces/$workspaceId/peers/$peerId/chat'
      fullPath: '/workspaces/$workspaceId/peers/$peerId/chat'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPeersPeerIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ExploreRoute: ExploreRoute,
  FleetRoute: FleetRoute,
  GovernanceRoute: GovernanceRoute,
  ResourcesRoute: ResourcesRoute,
  SeedKitsRoute: SeedKitsRoute,
  SettingsRoute: SettingsRoute,
  TelemetryRoute: TelemetryRoute,
  WorkspacesRoute: WorkspacesRoute,
  DevDreamProgressRoute: DevDreamProgressRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  WorkspacesWorkspaceIdConclusionsRoute: WorkspacesWorkspaceIdConclusionsRoute,
  WorkspacesWorkspaceIdDreamsRoute: WorkspacesWorkspaceIdDreamsRoute,
  WorkspacesWorkspaceIdPeersRoute: WorkspacesWorkspaceIdPeersRoute,
  WorkspacesWorkspaceIdQueueRoute: WorkspacesWorkspaceIdQueueRoute,
  WorkspacesWorkspaceIdSessionsRoute: WorkspacesWorkspaceIdSessionsRoute,
  WorkspacesWorkspaceIdWebhooksRoute: WorkspacesWorkspaceIdWebhooksRoute,
  WorkspacesWorkspaceIdPeersPeerIdRoute: WorkspacesWorkspaceIdPeersPeerIdRoute,
  WorkspacesWorkspaceIdSessionsSessionIdRoute:
    WorkspacesWorkspaceIdSessionsSessionIdRoute,
  WorkspacesWorkspaceIdPeersPeerIdChatRoute:
    WorkspacesWorkspaceIdPeersPeerIdChatRoute,
  WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute:
    WorkspacesWorkspaceIdPeersPeerIdPlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
